platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  # install modules
  - npm install

test: off

build_script:
  - npm run build
